### ISSUE TITLE
GPU not used release19

### ISSUE THREAD

**Issue by pierreHaslee** [Unity-Technologies/ml-agents#5839]
# GPU not used
I don't see any CUDA GPU usage when training a ppo policy.

I have properly installed pytorch and cudatoolkit using conda.
```
torch.cuda.is_available()
```
returns True and I can display my GPU device name correctly, so the error should not be from this side.

## To Reproduce

My command line:
```
mlagents-learn ML-Agents\trainer_conf.yml --time-scale=20 --run-id recuriculum_boosts --resume --torch-device cuda
```

My training conf file:
[trainer_conf .txt](https://github.com/Unity-Technologies/ml-agents/files/10147173/trainer_conf.txt)
(uploaded as txt but is a yaml file as intended)

### training start:

![cmdline](https://user-images.githubusercontent.com/97137454/205457029-754952d0-13cc-4de5-9a79-f36df99d62e9.PNG)

### It is training properly (rewards are bad because I tweaked my config files to try and debug, but I was able to train my model):
![cmdTrain](https://user-images.githubusercontent.com/97137454/205457046-4ff2f2b9-e267-4fee-bc95-2bc3f9092fa1.PNG)

### My environment looks like this (not important):
![myEnv](https://user-images.githubusercontent.com/97137454/205457063-aa07b3db-83a0-403d-8acc-dcc7f4b2fc59.PNG)

### here is my GPU usage while training (pardon my french):
![usageTraining](https://user-images.githubusercontent.com/97137454/205457075-fe827b26-2d68-4aa4-8ac8-cf4e989741bf.PNG)

as you can see there is no CUDA mention, and when doing nvidia-smi, all processes show N/A as GPU usage.

### when I press play in Unity (no training), I actually have a higher GPU usage:
![usagePlaying](https://user-images.githubusercontent.com/97137454/205457358-9f75119a-46bf-418a-bc06-cbdf4ef60e69.PNG)

I hope there is a fix because I'd really appreciate the speed boost from my RTX.

I'd also like to thank the devs behind this RL implementation in unity as it is simply amazing, I am amazed by how well it works.

**Environment :**
- Unity Version:  Unity 2021.3.14f1
- OS + version: Windows 10
- _ML-Agents version_: 2.2.1-exp.1
- _Torch version_: torch 1.7.1+cu110
- _Environment_: my own env, **I tested it as well with GridWorld with the same results**.

**Comment by Eelam** [comment]
Did you install CUDA tool's from Nvidia?
If so, check your CUDA tool's version with the Torch version: torch 1.7.1+cu110.
I had an issue with the 'curiosity' parameter. I fixed it by installing the correct version of the CUDA tools: [https://github.com/Unity-Technologies/ml-agents/issues/5793](https://github.com/Unity-Technologies/ml-agents/issues/5793)

**Comment by miguelalonsojr** [comment]
We just cut release 20, can you update and give it a try?

**Comment by pierreHaslee** [comment]
I updated to release20 along with the new unity extensions and it did not change.
I also installed CUDA 11.6 from NVIDA, tried multiple versions of pytorch including the latest and nightly, nothing seems to be working.

**Comment by pierreHaslee** [comment]
Well I am sorry to have wasted your time, but I didn't see there was a Cuda option on the windows Task Manager Performances section...

![usageHere](https://user-images.githubusercontent.com/97137454/206828380-18f6d452-b346-4401-91b8-c140317403b1.PNG)

There is therefore no bug and everything works fine.
