### ISSUE TITLE
No support for RTX 4090 GPU

### ISSUE THREAD

**Issue by AIWithShrey** [Unity-Technologies/ml-agents#5973]
**Describe the bug**
PyTorch 1.* does not support a GPU with a compute capability of 8.9 which means I must upgrade to PyTorch 2.0 to train models on an RTX 4090. However, upgrading PyTorch to 2.0.1 breaks the ml-agents installation as ml-agents requires no more than PyTorch version 1.11 to be installed.

**To Reproduce**
1) Make sure your machine is equipped with an RTX 4090 by running ```nvidia-smi```
2) Clone this repo and ```cd``` into it. Then install the Python packages with ```pip3 install -e ./ml-agents-envs``` and ```pip3 install -e ./ml-agents```
3) Run an example. I followed HuggingFace's Huggy tutorial.
4) Finally, hit the command ```mlagents-learn <config-file-path> --env-dir=<env-dir> --run-id=<run-id-name> --no-graphics```

This should throw these errors:

**Console logs / stack traces**
```
NVIDIA GeForce RTX 4090 with CUDA capability sm_89 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 4090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
[WARNING] Trainer has no policies, not saving anything.
Traceback (most recent call last):
  File "/home/acm/.local/bin/mlagents-learn", line 33, in <module>
    sys.exit(load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')())
  File "/home/acm/ml-agents/ml-agents/mlagents/trainers/learn.py", line 264, in main
    run_cli(parse_command_line())
  File "/home/acm/ml-agents/ml-agents/mlagents/trainers/learn.py", line 260, in run_cli
    run_training(run_seed, options, num_areas)
  File "/home/acm/ml-agents/ml-agents/mlagents/trainers/learn.py", line 136, in run_training
    tc.start_learning(env_manager)
  File "/home/acm/ml-agents/ml-agents-envs/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/home/acm/ml-agents/ml-agents/mlagents/trainers/trainer_controller.py", line 172, in start_learning
    self._reset_env(env_manager)
  File "/home/acm/ml-agents/ml-agents-envs/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/home/acm/ml-agents/ml-agents/mlagents/trainers/trainer_controller.py", line 107, in _reset_env
    self._register_new_behaviors(env_manager, env_manager.first_step_infos)
  File "/home/acm/ml-agents/ml-agents/mlagents/trainers/trainer_controller.py", line 267, in _register_new_behaviors
    self._create_trainers_and_managers(env_manager, new_behavior_ids)
  File "/home/acm/ml-agents/ml-agents/mlagents/trainers/trainer_controller.py", line 165, in _create_trainers_and_managers
    self._create_trainer_and_manager(env_manager, behavior_id)
  File "/home/acm/ml-agents/ml-agents/mlagents/trainers/trainer_controller.py", line 137, in _create_trainer_and_manager
    policy = trainer.create_policy(
  File "/home/acm/ml-agents/ml-agents/mlagents/trainers/ppo/trainer.py", line 194, in create_policy
    policy = TorchPolicy(
  File "/home/acm/ml-agents/ml-agents/mlagents/trainers/policy/torch_policy.py", line 41, in __init__
    GlobalSteps()
  File "/home/acm/ml-agents/ml-agents/mlagents/trainers/torch_entities/networks.py", line 748, in __init__
    torch.Tensor([0]).to(torch.int64), requires_grad=False
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Environment:**
- Unity Environment Package Version: 2.2.1-exp.1
- Communication Version: 1.5.0
- OS + version: Ubuntu 22.04 LTS
- _ML-Agents version_: ML-Agents v0.31.0.dev0 
- _Torch version_: 1.11.0+cu102
- _Environment_: Huggy (From HuggingFace)

I really need this working for a competition at my university. Any help is greatly appreciated.

**Comment by AIWithShrey** [comment]
I found a fix to my problem. I had to install a version of PyTorch 1.1 that is compatible with CUDA 11.3 (torch 1.11+cu113), hope this helps anyone stuck on the same issue.
